name: CI

on:
  push:
    paths:
      - 'src/*.py'
      - 'tests/*.py'
  pull_request:
    paths:
      - 'src/*.py'
      - 'tests/*.py'

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies for Mac and Linux
      if: runner.os != 'Windows'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install dependencies for Windows
      if: runner.os == 'Windows'
      run: |
        python -m pip install --upgrade pip
        pip install pywin32==306
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        pytest tests/
