name: Python Tests with pytest

on:
  push:
    paths:
      - 'src/*.py'
      - 'tests/*.py'
  pull_request:
    paths:
      - 'src/*.py'
      - 'tests/*.py'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Specify the Python version you need
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt # Replace with your requirements file, if you have one
    - name: Run tests with pytest
      run: |
        pytest tests/
